# Generated by Django 5.1.6 on 2025-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0013_alter_m3ufilter_filter_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m3ufilter',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='m3ufilter',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
