# Generated by Django 5.1.6 on 2025-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0012_alter_m3uaccount_refresh_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3ufilter',
            name='filter_type',
            field=models.CharField(choices=[('group', 'Group'), ('name', 'Stream Name'), ('url', 'Stream URL')], default='group', help_text='Filter based on either group title or stream name.', max_length=50),
        ),
    ]
