# Generated by Django 5.2.4 on 2025-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_channel_groups_user_channel_profiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
