# Generated by Django 5.2.11 on 2026-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
