#!/bin/bash

# Dispatcharr Enhancements - Verbesserte Version v2
# Korrigiert Frontend-Integration und Failover-Logik

set -e

echo "=== Applying Dispatcharr Enhancements v2 ==="

# 1. MAX_RETRIES von 3 auf 2 reduzieren
echo "1. Updating MAX_RETRIES..."
if [ -f "apps/proxy/config.py" ]; then
    if grep -q "MAX_RETRIES = 3" apps/proxy/config.py; then
        sed -i 's/MAX_RETRIES = 3/MAX_RETRIES = 2/g' apps/proxy/config.py
        echo "   ✓ MAX_RETRIES updated to 2"
    else
        echo "   ℹ MAX_RETRIES already modified or not found"
    fi
else
    echo "   ✗ apps/proxy/config.py not found"
fi

# 2. Proxy-Feld zu M3UAccount hinzufügen (nur wenn nicht vorhanden)
echo "2. Adding proxy field to M3UAccount..."
if [ -f "apps/m3u/models.py" ]; then
    if grep -q "proxy.*models.CharField" apps/m3u/models.py; then
        echo "   ✓ Proxy field already exists"
    else
        # Suche nach priority Feld und füge danach hinzu
        if grep -n "priority = models.PositiveIntegerField" apps/m3u/models.py; then
            # Finde die Zeile nach dem priority Feld und füge proxy hinzu
            sed -i '/priority = models.PositiveIntegerField(/,/)$/{
                /)$/{
                    a\
    proxy = models.CharField(\
        max_length=500,\
        blank=True,\
        null=True,\
        help_text="HTTP proxy URL for FFmpeg streams (e.g., http://proxy:8080)",\
    )
                }
            }' apps/m3u/models.py
            echo "   ✓ Proxy field added to M3UAccount model"
        else
            echo "   ⚠ Could not find priority field - proxy field not added"
        fi
    fi
else
    echo "   ✗ apps/m3u/models.py not found"
fi

# 3. Migration erstellen (nur wenn nicht vorhanden)
echo "3. Creating migration file..."
if [ -f "apps/m3u/migrations/0019_m3uaccount_proxy.py" ]; then
    echo "   ✓ Migration already exists"
else
    cat > apps/m3u/migrations/0019_m3uaccount_proxy.py << 'EOF'
# Generated by Django 5.2.4 on 2025-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0018_add_profile_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='proxy',
            field=models.CharField(blank=True, help_text='HTTP proxy URL for FFmpeg streams (e.g., http://proxy:8080)', max_length=500, null=True),
        ),
    ]
EOF
    echo "   ✓ Migration file created"
fi

# 4. Basic Auth Funktionen zu output/views.py hinzufügen (nur wenn nicht vorhanden)
echo "4. Adding Basic Auth to output views..."
if [ -f "apps/output/views.py" ]; then
    if grep -q "get_basic_auth_user" apps/output/views.py; then
        echo "   ✓ Basic Auth functions already exist"
    else
        # Füge Basic Auth Funktionen nach logger hinzu
        sed -i '/^logger = logging.getLogger(__name__)$/a\
\
def get_basic_auth_user(request):\
    """Extract and validate user from HTTP Basic Authentication header."""\
    auth_header = request.META.get("HTTP_AUTHORIZATION", "")\
    if not auth_header.startswith("Basic "):\
        return None\
    try:\
        encoded_credentials = auth_header[6:]\
        decoded_credentials = base64.b64decode(encoded_credentials).decode("utf-8")\
        username, password = decoded_credentials.split(":", 1)\
        try:\
            user = User.objects.get(username=username)\
        except User.DoesNotExist:\
            return None\
        if not user.check_password(password) or not user.is_active:\
            return None\
        return user\
    except (ValueError, UnicodeDecodeError):\
        return None\
\
def require_basic_auth(request):\
    """Return a 401 response requesting Basic Authentication."""\
    response = HttpResponse("Authentication required", status=401)\
    response["WWW-Authenticate"] = "Basic realm=\\"Dispatcharr\\""\
    return response' apps/output/views.py

        # Füge Basic Auth Check zu m3u_endpoint hinzu
        sed -i '/return JsonResponse({"error": "Forbidden"}, status=403)/a\
\
    # Require Basic Auth if no user provided\
    if user is None:\
        user = get_basic_auth_user(request)\
        if user is None:\
            return require_basic_auth(request)' apps/output/views.py

        echo "   ✓ Basic Auth functions added"
    fi
else
    echo "   ✗ apps/output/views.py not found"
fi

# 5. Frontend M3U Form aktualisieren - VERBESSERTE VERSION
echo "5. Updating frontend M3U form..."
if [ -f "frontend/src/components/forms/M3U.jsx" ]; then
    if grep -q '"proxy"' frontend/src/components/forms/M3U.jsx; then
        echo "   ✓ Proxy field already exists in frontend"
    else
        echo "   → Adding proxy field to frontend form..."
        
        # 5a. Füge proxy zu initialValues hinzu (nach enable_vod)
        if grep -q "enable_vod: false," frontend/src/components/forms/M3U.jsx; then
            sed -i '/enable_vod: false,/a\
      proxy: "",' frontend/src/components/forms/M3U.jsx
            echo "   ✓ Added proxy to initialValues"
        fi
        
        # 5b. Füge proxy zu form.setValues hinzu (nach enable_vod)
        if grep -q "enable_vod: m3uAccount.enable_vod || false," frontend/src/components/forms/M3U.jsx; then
            sed -i '/enable_vod: m3uAccount.enable_vod || false,/a\
        proxy: m3uAccount.proxy || "",' frontend/src/components/forms/M3U.jsx
            echo "   ✓ Added proxy to form.setValues"
        fi
        
        # 5c. Füge Proxy TextInput nach server_url TextInput hinzu
        # Suche nach der schließenden /> des server_url TextInputs
        if grep -A 5 'id="server_url"' frontend/src/components/forms/M3U.jsx | grep -q 'key={form.key.*server_url'; then
            # Finde die Zeile mit key={form.key('server_url')} und füge danach hinzu
            sed -i '/key={form\.key.*server_url.*}/a\
\
              <TextInput\
                style={{ width: "100%" }}\
                id="proxy"\
                name="proxy"\
                label="HTTP Proxy"\
                placeholder="http://proxy:8080"\
                description="HTTP proxy URL for FFmpeg streams (optional)"\
                {...form.getInputProps("proxy")}\
                key={form.key("proxy")}\
              />' frontend/src/components/forms/M3U.jsx
            echo "   ✓ Added proxy TextInput after server_url"
        else
            echo "   ⚠ Could not find server_url TextInput - proxy field not added to UI"
        fi
        
        echo "   ✓ Frontend proxy field integration completed"
    fi
else
    echo "   ℹ Frontend not found - skipping (will work via API)"
fi

# 6. Verbesserte Failover-Logik in channels/models.py
echo "6. Enhancing failover logic..."
if [ -f "apps/channels/models.py" ]; then
    # Prüfe ob bereits erweitert
    if grep -q "tried_profiles = set()" apps/channels/models.py; then
        echo "   ✓ Failover logic already enhanced"
    else
        echo "   → Enhancing profile failover logic..."
        
        # 6a. Füge Tracking-Variablen hinzu
        if grep -q "has_streams_but_maxed_out = False" apps/channels/models.py; then
            sed -i '/has_streams_but_maxed_out = False/a\
        tried_profiles = set()  # Track tried profiles for failover\
        failed_profiles = []    # Track failed profiles with reasons' apps/channels/models.py
            echo "   ✓ Added failover tracking variables"
        fi
        
        # 6b. Verbessere die Profile-Iteration mit Failover-Logik
        # Suche nach "for profile in profiles:" und erweitere die Logik
        if grep -q "for profile in profiles:" apps/channels/models.py; then
            # Füge Profile-Tracking nach der for-Schleife hinzu
            sed -i '/for profile in profiles:/a\
                profile_id = profile.id\
                \
                # Skip if profile already tried\
                if profile_id in tried_profiles:\
                    continue\
                    \
                # Mark profile as tried\
                tried_profiles.add(profile_id)\
                \
                # Skip inactive profiles\
                if not profile.is_active:\
                    failed_profiles.append({\
                        "profile_id": profile_id,\
                        "reason": "Profile is inactive",\
                        "stream_id": stream.id\
                    })\
                    continue' apps/channels/models.py
            echo "   ✓ Enhanced profile iteration with failover logic"
        fi
        
        # 6c. Verbessere Fehlerberichterstattung
        if grep -q "No available streams - determine specific reason" apps/channels/models.py; then
            sed -i '/No available streams - determine specific reason/a\
        \
        # Enhanced error reporting with failover details\
        if failed_profiles:\
            profile_details = "; ".join([f"Profile {p[\"profile_id\"]} (Stream {p[\"stream_id\"]}): {p[\"reason\"]}" for p in failed_profiles])\
            if has_streams_but_maxed_out:\
                error_reason += f" - Tried profiles: {len(tried_profiles)}, Failed: {profile_details}"\
            else:\
                error_reason = f"Profile failover failed - {profile_details}"\
        \
        logger.warning(f"Channel {self.id} stream assignment failed after trying {len(tried_profiles)} profiles: {error_reason}")' apps/channels/models.py
            echo "   ✓ Enhanced error reporting with failover details"
        fi
        
        echo "   ✓ Profile failover logic enhancement completed"
    fi
else
    echo "   ✗ apps/channels/models.py not found"
fi

# 7. Python-Syntax prüfen
echo "7. Validating Python syntax..."
python_files=("apps/proxy/config.py" "apps/m3u/models.py" "apps/output/views.py" "apps/channels/models.py")
syntax_errors=0

for file in "${python_files[@]}"; do
    if [ -f "$file" ]; then
        if python3 -m py_compile "$file" 2>/dev/null; then
            echo "   ✓ $file syntax OK"
        else
            echo "   ✗ $file has syntax errors!"
            python3 -m py_compile "$file" || true  # Show the error
            syntax_errors=$((syntax_errors + 1))
        fi
    fi
done

# 8. Frontend-Syntax prüfen (falls Node.js verfügbar)
echo "8. Validating Frontend syntax..."
if [ -f "frontend/src/components/forms/M3U.jsx" ] && command -v node >/dev/null 2>&1; then
    if node -c frontend/src/components/forms/M3U.jsx 2>/dev/null; then
        echo "   ✓ M3U.jsx syntax OK"
    else
        echo "   ⚠ M3U.jsx may have syntax issues"
    fi
else
    echo "   ℹ Node.js not available or frontend not found - skipping JS validation"
fi

if [ $syntax_errors -gt 0 ]; then
    echo "   ⚠ $syntax_errors files have syntax errors - please check manually"
    exit 1
else
    echo "   ✓ All Python files have valid syntax"
fi

echo ""
echo "✓ All enhancements applied successfully!"
echo ""
echo "Changes made:"
echo "- MAX_RETRIES reduced from 3 to 2"
echo "- Added proxy field to M3UAccount model with migration"
echo "- Added Basic Auth for M3U/EPG output"
echo "- Enhanced profile failover logic with detailed tracking"
echo "- Added proxy field to frontend M3U form"
echo ""
echo "After build: Migration will be applied automatically on container start"