#!/bin/bash

# Dispatcharr Enhancements - Einfache und sichere Version
# Nur die funktionierenden Teile ohne komplexe Failover-Änderungen

set -e

echo "=== Applying Dispatcharr Enhancements (Simple & Safe) ==="

# 1. MAX_RETRIES von 3 auf 2 reduzieren
echo "1. Updating MAX_RETRIES..."
if [ -f "apps/proxy/config.py" ] && grep -q "MAX_RETRIES = 3" apps/proxy/config.py; then
    sed -i 's/MAX_RETRIES = 3/MAX_RETRIES = 2/g' apps/proxy/config.py
    echo "   ✓ MAX_RETRIES updated to 2"
else
    echo "   ℹ MAX_RETRIES already modified or not found"
fi

# 2. Proxy-Feld zu M3UAccount hinzufügen (nur wenn nicht vorhanden)
echo "2. Adding proxy field to M3UAccount..."
if [ -f "apps/m3u/models.py" ]; then
    if grep -q "proxy.*models.CharField" apps/m3u/models.py; then
        echo "   ✓ Proxy field already exists"
    else
        # Einfache Methode: Füge am Ende der M3UAccount Klasse hinzu
        # Suche nach der letzten Zeile vor def __str__(self)
        if grep -n "def __str__(self):" apps/m3u/models.py | head -1; then
            line_num=$(grep -n "def __str__(self):" apps/m3u/models.py | head -1 | cut -d: -f1)
            line_num=$((line_num - 1))
            
            # Füge Proxy-Feld vor __str__ hinzu
            sed -i "${line_num}a\\
    proxy = models.CharField(\\
        max_length=500,\\
        blank=True,\\
        null=True,\\
        help_text=\"HTTP proxy URL for FFmpeg streams (e.g., http://proxy:8080)\",\\
    )\\
" apps/m3u/models.py
            echo "   ✓ Proxy field added to M3UAccount model"
        else
            echo "   ⚠ Could not find insertion point - proxy field not added"
        fi
    fi
else
    echo "   ✗ apps/m3u/models.py not found"
fi

# 3. Migration erstellen (nur wenn nicht vorhanden)
echo "3. Creating migration file..."
if [ ! -f "apps/m3u/migrations/0019_m3uaccount_proxy.py" ]; then
    cat > apps/m3u/migrations/0019_m3uaccount_proxy.py << 'EOF'
# Generated by Django 5.2.4 on 2025-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0018_add_profile_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='proxy',
            field=models.CharField(blank=True, help_text='HTTP proxy URL for FFmpeg streams (e.g., http://proxy:8080)', max_length=500, null=True),
        ),
    ]
EOF
    echo "   ✓ Migration file created"
else
    echo "   ✓ Migration already exists"
fi

# 4. Basic Auth Funktionen zu output/views.py hinzufügen (nur wenn nicht vorhanden)
echo "4. Adding Basic Auth to output views..."
if [ -f "apps/output/views.py" ]; then
    if ! grep -q "get_basic_auth_user" apps/output/views.py; then
        # Füge Basic Auth Funktionen nach logger hinzu
        sed -i '/^logger = logging.getLogger(__name__)$/a\
\
def get_basic_auth_user(request):\
    """Extract and validate user from HTTP Basic Authentication header."""\
    auth_header = request.META.get("HTTP_AUTHORIZATION", "")\
    if not auth_header.startswith("Basic "):\
        return None\
    try:\
        encoded_credentials = auth_header[6:]\
        decoded_credentials = base64.b64decode(encoded_credentials).decode("utf-8")\
        username, password = decoded_credentials.split(":", 1)\
        try:\
            user = User.objects.get(username=username)\
        except User.DoesNotExist:\
            return None\
        if not user.check_password(password) or not user.is_active:\
            return None\
        return user\
    except (ValueError, UnicodeDecodeError):\
        return None\
\
def require_basic_auth(request):\
    """Return a 401 response requesting Basic Authentication."""\
    response = HttpResponse("Authentication required", status=401)\
    response["WWW-Authenticate"] = "Basic realm=\\"Dispatcharr\\""\
    return response' apps/output/views.py

        # Füge Basic Auth Check zu m3u_endpoint hinzu
        sed -i '/return JsonResponse({"error": "Forbidden"}, status=403)/a\
\
    # Require Basic Auth if no user provided\
    if user is None:\
        user = get_basic_auth_user(request)\
        if user is None:\
            return require_basic_auth(request)' apps/output/views.py

        echo "   ✓ Basic Auth functions added"
    else
        echo "   ✓ Basic Auth functions already exist"
    fi
else
    echo "   ✗ apps/output/views.py not found"
fi

# 5. Frontend M3U Form aktualisieren - NUR WENN FRONTEND VORHANDEN
echo "5. Updating frontend M3U form..."
if [ -f "frontend/src/components/forms/M3U.jsx" ]; then
    if ! grep -q '"proxy"' frontend/src/components/forms/M3U.jsx; then
        echo "   → Adding proxy field to frontend form..."
        
        # 5a. Füge proxy zu initialValues hinzu
        if grep -q "enable_vod: false," frontend/src/components/forms/M3U.jsx; then
            sed -i '/enable_vod: false,/a\
      proxy: "",' frontend/src/components/forms/M3U.jsx
            echo "   ✓ Added proxy to initialValues"
        fi
        
        # 5b. Füge proxy zu form.setValues hinzu
        if grep -q "enable_vod: m3uAccount.enable_vod || false," frontend/src/components/forms/M3U.jsx; then
            sed -i '/enable_vod: m3uAccount.enable_vod || false,/a\
        proxy: m3uAccount.proxy || "",' frontend/src/components/forms/M3U.jsx
            echo "   ✓ Added proxy to form.setValues"
        fi
        
        # 5c. Füge Proxy TextInput nach server_url hinzu
        # Suche nach der Zeile mit server_url key und füge danach hinzu
        if grep -n 'key={form\.key.*server_url' frontend/src/components/forms/M3U.jsx; then
            line_num=$(grep -n 'key={form\.key.*server_url' frontend/src/components/forms/M3U.jsx | cut -d: -f1)
            
            # Füge nach dieser Zeile das Proxy-Feld hinzu
            sed -i "${line_num}a\\
\\
              <TextInput\\
                style={{ width: \"100%\" }}\\
                id=\"proxy\"\\
                name=\"proxy\"\\
                label=\"HTTP Proxy\"\\
                placeholder=\"http://proxy:8080\"\\
                description=\"HTTP proxy URL for FFmpeg streams (optional)\"\\
                {...form.getInputProps(\"proxy\")}\\
                key={form.key(\"proxy\")}\\
              />" frontend/src/components/forms/M3U.jsx
            echo "   ✓ Added proxy TextInput after server_url"
        else
            echo "   ⚠ Could not find server_url field - proxy field not added to UI"
        fi
        
        echo "   ✓ Frontend proxy field integration completed"
    else
        echo "   ✓ Proxy field already exists in frontend"
    fi
else
    echo "   ℹ Frontend not found - skipping (will work via API)"
fi

# 6. Python-Syntax prüfen (nur die geänderten Dateien)
echo "6. Validating Python syntax..."
python_files=("apps/proxy/config.py" "apps/m3u/models.py" "apps/output/views.py")
syntax_errors=0

for file in "${python_files[@]}"; do
    if [ -f "$file" ]; then
        if python3 -m py_compile "$file" 2>/dev/null; then
            echo "   ✓ $file syntax OK"
        else
            echo "   ✗ $file has syntax errors!"
            python3 -m py_compile "$file" 2>&1 | head -5
            syntax_errors=$((syntax_errors + 1))
        fi
    fi
done

if [ $syntax_errors -gt 0 ]; then
    echo "   ⚠ $syntax_errors files have syntax errors - build will fail"
    exit 1
fi

echo ""
echo "✓ Essential enhancements applied successfully!"
echo ""
echo "Applied changes:"
echo "- MAX_RETRIES reduced from 3 to 2"
echo "- Added proxy field to M3UAccount model"
echo "- Created migration 0019_m3uaccount_proxy.py"
echo "- Added Basic Auth for M3U/EPG output"
echo "- Added proxy field to frontend M3U form (if frontend available)"
echo ""
echo "Note: Advanced failover logic skipped to avoid syntax errors"
echo "Basic profile failover still works through existing Django model logic"