#!/bin/bash

# Dispatcharr Enhancements - Automatische Anwendung beim Docker Build
# Einfach in Dockerfile hinzufügen: RUN ./apply_enhancements.sh

set -e

echo "=== Applying Dispatcharr Enhancements ==="

# 1. MAX_RETRIES von 3 auf 2 reduzieren
echo "1. Updating MAX_RETRIES..."
sed -i 's/MAX_RETRIES = 3/MAX_RETRIES = 2/g' apps/proxy/config.py

# 2. Proxy-Feld zu M3UAccount hinzufügen
echo "2. Adding proxy field to M3UAccount..."
if ! grep -q "proxy.*models.CharField" apps/m3u/models.py; then
    sed -i '/priority = models.PositiveIntegerField(/a\
    proxy = models.CharField(\
        max_length=500,\
        blank=True,\
        null=True,\
        help_text="HTTP proxy URL for FFmpeg streams (e.g., http://proxy:8080)",\
    )' apps/m3u/models.py
fi

# 3. Migration erstellen
echo "3. Creating migration file..."
cat > apps/m3u/migrations/0019_m3uaccount_proxy.py << 'EOF'
# Generated by Django 5.2.4 on 2025-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0018_add_profile_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='proxy',
            field=models.CharField(blank=True, help_text='HTTP proxy URL for FFmpeg streams (e.g., http://proxy:8080)', max_length=500, null=True),
        ),
    ]
EOF

# 4. Basic Auth Funktionen zu output/views.py hinzufügen
echo "4. Adding Basic Auth to output views..."
if ! grep -q "get_basic_auth_user" apps/output/views.py; then
    # Füge Basic Auth Funktionen nach logger hinzu
    sed -i '/^logger = logging.getLogger(__name__)$/a\
\
def get_basic_auth_user(request):\
    """Extract and validate user from HTTP Basic Authentication header."""\
    auth_header = request.META.get("HTTP_AUTHORIZATION", "")\
    if not auth_header.startswith("Basic "):\
        return None\
    try:\
        encoded_credentials = auth_header[6:]\
        decoded_credentials = base64.b64decode(encoded_credentials).decode("utf-8")\
        username, password = decoded_credentials.split(":", 1)\
        try:\
            user = User.objects.get(username=username)\
        except User.DoesNotExist:\
            return None\
        if not user.check_password(password) or not user.is_active:\
            return None\
        return user\
    except (ValueError, UnicodeDecodeError):\
        return None\
\
def require_basic_auth(request):\
    """Return a 401 response requesting Basic Authentication."""\
    response = HttpResponse("Authentication required", status=401)\
    response["WWW-Authenticate"] = "Basic realm=\\"Dispatcharr\\""\
    return response' apps/output/views.py

    # Füge Basic Auth Check zu m3u_endpoint hinzu
    sed -i '/return JsonResponse({"error": "Forbidden"}, status=403)/a\
\
    # Require Basic Auth if no user provided\
    if user is None:\
        user = get_basic_auth_user(request)\
        if user is None:\
            return require_basic_auth(request)' apps/output/views.py

    # Füge Basic Auth Check zu epg_endpoint hinzu (falls vorhanden)
    if grep -q "def epg_endpoint" apps/output/views.py; then
        sed -i '/def epg_endpoint/,/return generate_epg/ {
            /return JsonResponse({"error": "Forbidden"}, status=403)/a\
\
    # Require Basic Auth if no user provided\
    if user is None:\
        user = get_basic_auth_user(request)\
        if user is None:\
            return require_basic_auth(request)
        }' apps/output/views.py
    fi
fi

# 5. Frontend M3U Form aktualisieren (falls vorhanden)
echo "5. Updating frontend M3U form..."
if [ -f "frontend/src/components/forms/M3U.jsx" ]; then
    if ! grep -q "proxy.*TextInput" frontend/src/components/forms/M3U.jsx; then
        # Füge proxy zu initialValues hinzu
        sed -i '/enable_vod: false,/a\
      proxy: "",' frontend/src/components/forms/M3U.jsx
        
        # Füge proxy zu form.setValues hinzu
        sed -i '/enable_vod: m3uAccount.enable_vod || false,/a\
        proxy: m3uAccount.proxy || "",' frontend/src/components/forms/M3U.jsx
        
        # Füge Proxy TextInput nach server_url hinzu
        sed -i '/key={form.key("server_url")}/a\
\
              <TextInput\
                style={{ width: "100%" }}\
                id="proxy"\
                name="proxy"\
                label="HTTP Proxy"\
                placeholder="http://proxy:8080"\
                description="HTTP proxy URL for FFmpeg streams (optional)"\
                {...form.getInputProps("proxy")}\
                key={form.key("proxy")}\
              />' frontend/src/components/forms/M3U.jsx
    fi
else
    echo "   Frontend not found - skipping (will work via API)"
fi

# 6. Verbesserte Failover-Logik in channels/models.py
echo "6. Enhancing failover logic..."
if ! grep -q "tried_profiles = set()" apps/channels/models.py; then
    # Füge Failover-Tracking hinzu
    sed -i '/has_streams_but_maxed_out = False/a\
        tried_profiles = set()  # Track tried profiles for failover\
        failed_profiles = []    # Track failed profiles with reasons' apps/channels/models.py
    
    # Verbessere Profile-Iteration
    sed -i '/for profile in profiles:/a\
                profile_id = profile.id\
                if profile_id in tried_profiles:\
                    continue\
                tried_profiles.add(profile_id)' apps/channels/models.py
fi

echo "✓ All enhancements applied successfully!"
echo ""
echo "Changes made:"
echo "- MAX_RETRIES reduced from 3 to 2"
echo "- Added proxy field to M3UAccount model"
echo "- Created migration 0019_m3uaccount_proxy.py"
echo "- Added Basic Auth for M3U/EPG output"
echo "- Enhanced failover logic with profile tracking"
echo "- Updated frontend form (if present)"
echo ""
echo "After build: Run 'python manage.py migrate' to apply database changes"