services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr-dev
    ports:
      - "9197:9191"
    volumes:
      - /mnt/user/appdata/dispatcharr-dev/data3/:/data
      - /mnt/user/appdata/dispatcharr-dev/data/sources/:/app/sources
    environment:
      - TZ=America/Los_Angeles
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
      - M3U_BASIC_AUTH_ENABLED=true
      - M3U_BASIC_AUTH_REALM=Dispatcharr M3U
      - DISPATCHARR_DEBUG=false
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Tower
      - HOST_CONTAINERNAME=Dispatcharr-DEV
    devices:
      - /dev/dri:/dev/dri
    networks:
      - wg0
    pids_limit: 3072
    hostname: dispatcharr
    labels:
      - "net.unraid.docker.managed=dockerman"
      - "net.unraid.docker.webui=http://[IP]:[PORT:9191]"
      - "net.unraid.docker.icon=https://github.com/Dispatcharr/Dispatcharr/blob/main/frontend/src/images/logo.png?raw=true"

networks:
  wg0:
    external: true