# Generated by Django 5.1.6 on 2025-12-17 12:00

from django.db import migrations

def add_proxy_support_profiles(apps, schema_editor):
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    # Update existing ffmpeg profile to support proxy
    try:
        ffmpeg_profile = StreamProfile.objects.get(profile_name="ffmpeg")
        # Update parameters to include proxy support
        ffmpeg_profile.parameters = "-user_agent {userAgent} {proxy} -i {streamUrl} -c:v copy -c:a copy -f mpegts pipe:1"
        ffmpeg_profile.save()
    except StreamProfile.DoesNotExist:
        # Create new ffmpeg profile with proxy support if it doesn't exist
        StreamProfile.objects.create(
            profile_name="ffmpeg",
            command="ffmpeg",
            parameters="-user_agent {userAgent} {proxy} -i {streamUrl} -c:v copy -c:a copy -f mpegts pipe:1",
            is_active=True,
            user_agent="1",
        )
    
    # Create a new profile specifically for proxy-enabled streaming
    StreamProfile.objects.get_or_create(
        profile_name="ffmpeg-proxy",
        defaults={
            "command": "ffmpeg",
            "parameters": "-user_agent {userAgent} {proxy} -i {streamUrl} -c copy -f mpegts pipe:1",
            "is_active": True,
            "user_agent": "1",
        }
    )

def reverse_proxy_support_profiles(apps, schema_editor):
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    # Revert ffmpeg profile to original parameters
    try:
        ffmpeg_profile = StreamProfile.objects.get(profile_name="ffmpeg")
        ffmpeg_profile.parameters = "-i {streamUrl} -c:v copy -c:a copy -f mpegts pipe:1"
        ffmpeg_profile.save()
    except StreamProfile.DoesNotExist:
        pass
    
    # Remove the proxy-specific profile
    try:
        StreamProfile.objects.get(profile_name="ffmpeg-proxy").delete()
    except StreamProfile.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_proxy_and_redirect_stream_profiles'),
    ]

    operations = [
        migrations.RunPython(add_proxy_support_profiles, reverse_proxy_support_profiles),
    ]