# Generated by Django 5.1.6 on 2025-12-17 12:00

from django.db import migrations

def add_proxy_support_profiles(apps, schema_editor):
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    # Update existing ffmpeg profile - proxy is now handled in build_command()
    try:
        ffmpeg_profile = StreamProfile.objects.get(name="ffmpeg")
        # Parameters without {proxy} placeholder - proxy is injected by build_command()
        ffmpeg_profile.parameters = "-user_agent {userAgent} -i {streamUrl} -c:v copy -c:a copy -f mpegts pipe:1"
        ffmpeg_profile.save()
    except StreamProfile.DoesNotExist:
        # Create new ffmpeg profile if it doesn't exist
        StreamProfile.objects.create(
            name="ffmpeg",
            command="ffmpeg",
            parameters="-user_agent {userAgent} -i {streamUrl} -c:v copy -c:a copy -f mpegts pipe:1",
            is_active=True,
            user_agent_id=1,
        )

def reverse_proxy_support_profiles(apps, schema_editor):
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    # Revert ffmpeg profile to original parameters
    try:
        ffmpeg_profile = StreamProfile.objects.get(name="ffmpeg")
        ffmpeg_profile.parameters = "-i {streamUrl} -c:v copy -c:a copy -f mpegts pipe:1"
        ffmpeg_profile.save()
    except StreamProfile.DoesNotExist:
        pass
    
    # Remove the proxy-specific profile
    try:
        StreamProfile.objects.get(name="ffmpeg-proxy").delete()
    except StreamProfile.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coresettings_value_textfield'),
    ]

    operations = [
        migrations.RunPython(add_proxy_support_profiles, reverse_proxy_support_profiles),
    ]