# Generated by Django 5.2.11 on 2026-03-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream_limit',
            field=models.IntegerField(default=0),
        ),
    ]
