# Generated by Django 5.2.4 on 2025-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0015_alter_programdata_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgdata',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
