# Generated by Django 5.2.4 on 2025-09-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0016_epgdata_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgsource',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
