# Generated by Django 5.2.4 on 2025-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0020_migrate_time_to_starttime_placeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority for EPG matching (higher numbers = higher priority). Used when multiple EPG sources have matching entries for a channel.'),
        ),
    ]
