# Generated by Django 6.0.4 on 2026-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0021_epgsource_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgdata',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
