# Generated by Django 5.2.4 on 2025-09-04 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uepisoderelation',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this relation was seen during VOD scan'),
        ),
        migrations.AddField(
            model_name='m3umovierelation',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this relation was seen during VOD scan'),
        ),
        migrations.AddField(
            model_name='m3useriesrelation',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this relation was seen during VOD scan'),
        ),
    ]
