# Generated by Django 5.2.11 on 2026-02-24 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0003_vodlogo_alter_movie_logo_alter_series_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uepisoderelation',
            name='series_relation',
            field=models.ForeignKey(blank=True, help_text='The series relation this episode relation belongs to. CASCADE ensures cleanup when the series relation is removed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_relations', to='vod.m3useriesrelation'),
        ),
    ]
