# Generated by Django 5.1.6 on 2025-03-01 14:01

from django.db import migrations
from django.utils.text import slugify


def preload_user_limit_settings(apps, schema_editor):
    CoreSettings = apps.get_model("core", "CoreSettings")
    CoreSettings.objects.create(
        key="user_limit_settings",
        name="User Limit Settings",
        value={},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_systemnotification_notificationdismissal"),
    ]

    operations = [
        migrations.RunPython(preload_user_limit_settings),
    ]
