# Generated by Django 5.1.6 on 2025-07-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0022_channel_auto_created_channel_auto_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_stats',
            field=models.JSONField(blank=True, help_text='JSON object containing stream statistics like video codec, resolution, etc.', null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_stats_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When stream statistics were last updated', null=True),
        ),
    ]
