# Generated by Django 5.2.9 on 2026-01-09 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0030_alter_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='is_stale',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this group relationship is stale (not seen in recent refresh, pending deletion)'),
        ),
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, help_text='Last time this group was seen in the M3U source during a refresh'),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_stale',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this stream is stale (not seen in recent refresh, pending deletion)'),
        ),
    ]
