# Generated by Django 5.2.4 on 2025-10-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0029_backfill_custom_stream_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
    ]
