# Generated by Django 5.2.9 on 2026-02-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0033_stream_id_stream_chno'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stream',
            name='dispatcharr_stream_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='stream',
            name='dispatcharr_stream_chno_idx',
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_chno',
            field=models.FloatField(blank=True, db_index=True, help_text='Provider channel number (XC num or M3U tvg-chno) for ordering - supports decimals like 2.1', null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Provider stream ID (e.g., XC stream_id) for stable identity across credential changes', null=True),
        ),
    ]
