# Generated by Django 6.0.4 on 2026-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0034_remove_stream_dispatcharr_stream_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(default='Default Stream', max_length=512),
        ),
    ]
