# Generated by Django 6.0.4 on 2026-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0035_alter_channel_name_alter_stream_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(db_index=True, default='Default Stream', max_length=512),
        ),
    ]
