# Generated by Django 5.2.4 on 2025-08-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0023_stream_stream_stats_stream_stream_stats_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelgroupm3uaccount',
            name='channel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m3u_accounts', to='dispatcharr_channels.channelgroup'),
        ),
    ]
