# Generated by Django 5.2.4 on 2025-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0024_alter_channelgroupm3uaccount_channel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelgroupm3uaccount',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
