# Generated by Django 5.2.4 on 2025-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0026_recurringrecordingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringrecordingrule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringrecordingrule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
