# Generated by Django 5.2.9 on 2026-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0031_channelgroupm3uaccount_is_stale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this channel contains adult content'),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this stream contains adult content'),
        ),
    ]
