# Generated by Django 5.2.4 on 2025-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0014_epgsource_extracted_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdata',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
