# Generated by Django 5.2.4 on 2025-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0017_alter_epgsource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Custom properties for dummy EPG configuration (regex patterns, timezone, duration, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='epgsource',
            name='source_type',
            field=models.CharField(choices=[('xmltv', 'XMLTV URL'), ('schedules_direct', 'Schedules Direct API'), ('dummy', 'Custom Dummy EPG')], max_length=20),
        ),
    ]
