# Generated by Django 5.2.4 on 2025-10-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0018_epgsource_custom_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdata',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
