# Generated by Django 5.2.4 on 2025-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0014_alter_m3ufilter_options_m3ufilter_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m3ufilter',
            options={},
        ),
        migrations.AddField(
            model_name='m3ufilter',
            name='custom_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
