# Generated by Django 5.2.4 on 2025-08-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0015_alter_m3ufilter_options_m3ufilter_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority for VOD provider selection (higher numbers = higher priority). Used when multiple providers offer the same content.'),
        ),
    ]
