# Generated by Django 5.2.4 on 2025-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0016_m3uaccount_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3uaccount',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='m3uaccount',
            name='server_url',
            field=models.URLField(blank=True, help_text='The base URL of the M3U server (optional if a file is uploaded)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m3ufilter',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
