# Generated by Django 5.2.4 on 2025-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0017_alter_m3uaccount_custom_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccountprofile',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Custom properties for storing account information from provider (e.g., XC account details, expiration dates)', null=True),
        ),
    ]
