# Generated manually for M3UAccountMac model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0021_add_mac_support'),
    ]

    operations = [
        # Use RunSQL to safely create M3UAccountMac table if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 
                        FROM information_schema.tables 
                        WHERE table_name = 'm3u_m3uaccountmac'
                    ) THEN
                        CREATE TABLE "m3u_m3uaccountmac" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "address" varchar(17) NOT NULL,
                            "priority" integer NOT NULL CHECK ("priority" >= 0) DEFAULT 0,
                            "status" varchar(20) NOT NULL DEFAULT 'unknown',
                            "expires_at" timestamp with time zone NULL,
                            "expires_text" varchar(255) NULL,
                            "last_checked" timestamp with time zone NULL,
                            "last_error" text NULL,
                            "account_id" bigint NOT NULL
                        );
                        
                        -- Add foreign key constraint
                        ALTER TABLE "m3u_m3uaccountmac" 
                        ADD CONSTRAINT "m3u_m3uaccountmac_account_id_fkey" 
                        FOREIGN KEY ("account_id") REFERENCES "m3u_m3uaccount" ("id") 
                        DEFERRABLE INITIALLY DEFERRED;
                        
                        -- Add unique constraint
                        ALTER TABLE "m3u_m3uaccountmac" 
                        ADD CONSTRAINT "unique_account_mac" 
                        UNIQUE ("account_id", "address");
                        
                        -- Add index for ordering
                        CREATE INDEX "m3u_m3uaccountmac_priority_id_idx" 
                        ON "m3u_m3uaccountmac" ("priority", "id");
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS "m3u_m3uaccountmac";
            """,
        ),
    ]