# Generated manually for M3UAccountMac model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0021_add_mac_support'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='M3UAccountMac',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('address', models.CharField(max_length=17, help_text='MAC address in format AA:BB:CC:DD:EE:FF')),
                        ('priority', models.PositiveIntegerField(default=0, help_text='Priority order for failover (0 = highest priority)')),
                        ('status', models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('expired', 'Expired'), ('error', 'Error')], default='unknown', max_length=20, help_text='Current validation status of this MAC address')),
                        ('expires_at', models.DateTimeField(blank=True, null=True, help_text='When this MAC address expires (if known)')),
                        ('expires_text', models.CharField(blank=True, max_length=255, null=True, help_text='Raw expiry text from portal for display')),
                        ('last_checked', models.DateTimeField(blank=True, null=True, help_text='When this MAC was last validated')),
                        ('last_error', models.TextField(blank=True, null=True, help_text='Last error message if validation failed')),
                        ('account', models.ForeignKey(help_text='The M3U account this MAC belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='macs', to='m3u.m3uaccount')),
                    ],
                    options={
                        'verbose_name': 'MAC Address',
                        'verbose_name_plural': 'MAC Addresses',
                        'ordering': ['priority', 'id'],
                    },
                ),
                migrations.AddConstraint(
                    model_name='m3uaccountmac',
                    constraint=models.UniqueConstraint(fields=['account', 'address'], name='unique_account_mac'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "m3u_m3uaccountmac" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "address" varchar(17) NOT NULL,
                            "priority" integer NOT NULL DEFAULT 0 CHECK ("priority" >= 0),
                            "status" varchar(20) NOT NULL DEFAULT 'unknown',
                            "expires_at" timestamp with time zone NULL,
                            "expires_text" varchar(255) NULL,
                            "last_checked" timestamp with time zone NULL,
                            "last_error" text NULL,
                            "account_id" bigint NOT NULL REFERENCES "m3u_m3uaccount" ("id") DEFERRABLE INITIALLY DEFERRED
                        );
                        
                        CREATE UNIQUE INDEX IF NOT EXISTS "unique_account_mac" 
                        ON "m3u_m3uaccountmac" ("account_id", "address");
                        
                        CREATE INDEX IF NOT EXISTS "m3u_m3uaccountmac_priority_id_idx" 
                        ON "m3u_m3uaccountmac" ("priority", "id");
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "m3u_m3uaccountmac";',
                ),
            ],
        ),
    ]
