# Generated by Django 5.1.6 on 2025-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0035_clear_cached_portal_engine'),  # Latest migration
    ]

    operations = [
        # Safely add proxy field if it doesn't exist (for MAC/STB accounts)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 
                        FROM information_schema.columns 
                        WHERE table_name = 'm3u_m3uaccount' 
                        AND column_name = 'proxy'
                    ) THEN
                        ALTER TABLE m3u_m3uaccount 
                        ADD COLUMN proxy varchar(255);
                    END IF;
                END $$;
            """,
            reverse_sql="-- Don't drop proxy field in reverse",
        ),
        
        # Add the new proxy_std_xc field for STD/XC accounts
        migrations.AddField(
            model_name='m3uaccount',
            name='proxy_std_xc',
            field=models.CharField(
                blank=True,
                help_text='Proxy server for STD/XC connections (e.g., http://proxy:8080). Used for Standard and Xtream Codes accounts.',
                max_length=255,
                null=True,
                verbose_name='Proxy (STD/XC)'
            ),
        ),
    ]