# Generated by Django 5.1.6 on 2025-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0035_clear_cached_portal_engine'),  # Latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='proxy_std_xc',
            field=models.CharField(
                blank=True,
                help_text='Proxy server for STD/XC connections (e.g., http://proxy:8080). Used for Standard and Xtream Codes accounts.',
                max_length=255,
                null=True,
                verbose_name='Proxy (STD/XC)'
            ),
        ),
        migrations.AlterField(
            model_name='m3uaccount',
            name='proxy',
            field=models.CharField(
                blank=True,
                help_text='Proxy server for MAC portal connections (e.g., http://proxy:8080). Used only for MAC/STB Portal accounts.',
                max_length=255,
                null=True,
                verbose_name='Proxy (MAC/STB)'
            ),
        ),
    ]